### ISSUE TITLE
Cannot disable automatic bash autocompletion msg?

### ISSUE THREAD

**Issue by darkvertex** [posener/cmd#20]
I appreciate the feature exists but can it be turned off? I glanced at the codebase and didn't see an option.

I'm building an .exe for Windows and it makes no sense to be offering people Bash completion by default. (Ok, maybe for Cygwin, but still, not something I want in the `-h` output.)

**Comment by posener** [comment]
Make sense to hide the relevant help on windows. About disabling - does it make any harm?
It can be done using runtime.GOOS, no need for options.
Want to submit a pr?

**Comment by darkvertex** [comment]
It does no harm by existing, but in terms of the -h output, Windows aside, I personally dislike the choice that the msg is forced all the time anyway.

Just autohiding it on Windows would not satisfy me (plus what if it's running in Cygwin? Then it should display because Cygwin can run Bash but runtime.GOOS would still say it's Windows.)

I was tight on time so unfortunately I bailed on this library for another, sorry.

**Comment by posener** [comment]
Fixed by #25 
Thanks Jan! Great job!
